export const permissionMap = {
  legalCases: {
    view: "cases.view",
    list: "cases.list",
    search: "cases.search",
    create: "cases.create",
    update: "cases.update",
    delete: "cases.delete",
    changeStatus: "cases.change_status",
    close: "cases.close",
    reopen: "cases.reopen",
    assign: "cases.assign",
    reassign: "cases.reassign",
    attachmentsManage: "cases.attachments_manage",
    notesManage: "cases.notes_manage",
  },
  clients: {
    view: "clients.view",
    list: "clients.list",
    search: "clients.search",
    create: "clients.create",
    update: "clients.update",
    delete: "clients.delete",
    changeStatus: "clients.change_status",
    assign: "clients.assign",
    viewSensitive: "clients.view_sensitive",
  },
  sessions: {
    view: "sessions.view",
    list: "sessions.list",
    search: "sessions.search",
    create: "sessions.create",
    update: "sessions.update",
    delete: "sessions.delete",
    changeStatus: "sessions.change_status",
    assign: "sessions.assign",
    print: "sessions.print",
  },
  procedures: {
    view: "procedures.view",
    list: "procedures.list",
    search: "procedures.search",
    create: "procedures.create",
    update: "procedures.update",
    delete: "procedures.delete",
    changeStatus: "procedures.change_status",
    assign: "procedures.assign",
  },
  services: {
    view: "services.view",
    list: "services.list",
    search: "services.search",
    create: "services.create",
    update: "services.update",
    delete: "services.delete",
    changeStatus: "services.change_status",
    close: "services.close",
    reopen: "services.reopen",
  },
  courts: {
    view: "courts.view",
    list: "courts.list",
    search: "courts.search",
    create: "courts.create",
    update: "courts.update",
    delete: "courts.delete",
  },
  lawyers: {
    view: "lawyers.view",
    list: "lawyers.list",
    search: "lawyers.search",
    create: "lawyers.create",
    update: "lawyers.update",
    delete: "lawyers.delete",
    assign: "lawyers.assign",
  },
  reports: {
    view: "reports.view",
    list: "reports.list",
    search: "reports.search",
    filter: "reports.filter",
    export: "reports.export",
    print: "reports.print",
    auditView: "reports.audit_view",
  },
  adminUsers: {
    view: "users.view",
    list: "users.list",
    search: "users.search",
    create: "users.create",
    update: "users.update",
    delete: "users.delete",
    assignRoles: "users.assign_roles",
    changeStatus: "users.change_status",
  },
  adminRoles: {
    view: "roles.view",
    list: "roles.list",
    create: "roles.create",
    update: "roles.update",
    delete: "roles.delete",
    assignPermissions: "roles.assign_permissions",
  },
  adminPermissions: {
    view: "permissions.view",
    list: "permissions.list",
    search: "permissions.search",
  },
  settings: {
    view: "settings.view",
    update: "settings.update",
  },
} as const;

export type PermissionModuleKey = keyof typeof permissionMap;
export type ModulePermissions<TModule extends PermissionModuleKey = PermissionModuleKey> = (typeof permissionMap)[TModule];
export type PermissionName = (typeof permissionMap)[PermissionModuleKey][keyof (typeof permissionMap)[PermissionModuleKey]];

export const allPermissions = Array.from(new Set(Object.values(permissionMap).flatMap((modulePermissions) => Object.values(modulePermissions))));
