import { allPermissions, permissionMap, type PermissionName } from "@shared/security/permission-map";

type RoleName = "super_admin" | "admin" | "lawyer" | "assistant" | "accountant" | "viewer";

const set = (...permissions: PermissionName[]) => permissions;

const adminRestricted = new Set<PermissionName>([
  permissionMap.legalCases.delete,
  permissionMap.services.delete,
  permissionMap.expenses.delete,
  permissionMap.adminRoles.delete,
  permissionMap.adminUsers.delete,
]);

export const rolePermissionMap: Record<RoleName, PermissionName[]> = {
  super_admin: allPermissions,
  admin: allPermissions.filter((permission) => !adminRestricted.has(permission as PermissionName)),
  lawyer: set(
    permissionMap.dashboard.view,
    permissionMap.dashboard.search,
    permissionMap.legalCases.view,
    permissionMap.legalCases.list,
    permissionMap.legalCases.search,
    permissionMap.legalCases.update,
    permissionMap.legalCases.changeStatus,
    permissionMap.legalCases.notesManage,
    permissionMap.legalCases.attachmentsManage,
    permissionMap.sessions.view,
    permissionMap.sessions.list,
    permissionMap.sessions.search,
    permissionMap.sessions.create,
    permissionMap.sessions.update,
    permissionMap.sessions.changeStatus,
    permissionMap.sessions.print,
    permissionMap.procedures.view,
    permissionMap.procedures.list,
    permissionMap.procedures.search,
    permissionMap.procedures.create,
    permissionMap.procedures.update,
    permissionMap.procedures.changeStatus,
    permissionMap.procedures.print,
    permissionMap.clients.view,
    permissionMap.clients.list,
    permissionMap.clients.search,
    permissionMap.reports.view,
    permissionMap.reports.filter,
    permissionMap.notifications.viewOwn,
    permissionMap.notifications.markRead,
    permissionMap.events.view,
    permissionMap.settings.view,
    permissionMap.settings.manage,
  ),
  assistant: set(
    permissionMap.dashboard.view,
    permissionMap.dashboard.search,
    permissionMap.legalCases.view,
    permissionMap.legalCases.list,
    permissionMap.legalCases.search,
    permissionMap.legalCases.update,
    permissionMap.legalCases.notesManage,
    permissionMap.legalCases.attachmentsManage,
    permissionMap.sessions.view,
    permissionMap.sessions.list,
    permissionMap.sessions.search,
    permissionMap.procedures.view,
    permissionMap.procedures.list,
    permissionMap.procedures.search,
    permissionMap.clients.view,
    permissionMap.clients.list,
    permissionMap.clients.search,
    permissionMap.notifications.viewOwn,
    permissionMap.notifications.markRead,
    permissionMap.settings.view,
    permissionMap.settings.manage,
  ),
  accountant: set(
    permissionMap.dashboard.view,
    permissionMap.expenses.view,
    permissionMap.expenses.list,
    permissionMap.expenses.search,
    permissionMap.expenses.create,
    permissionMap.expenses.update,
    permissionMap.expenses.approve,
    permissionMap.expenses.reject,
    permissionMap.expenses.export,
    permissionMap.reports.view,
    permissionMap.reports.filter,
    permissionMap.reports.export,
    permissionMap.settings.view,
    permissionMap.settings.manage,
  ),
  viewer: set(
    permissionMap.dashboard.view,
    permissionMap.legalCases.view,
    permissionMap.legalCases.list,
    permissionMap.legalCases.search,
    permissionMap.sessions.view,
    permissionMap.sessions.list,
    permissionMap.procedures.view,
    permissionMap.procedures.list,
    permissionMap.services.view,
    permissionMap.services.list,
    permissionMap.clients.view,
    permissionMap.clients.list,
    permissionMap.reports.view,
    permissionMap.reports.filter,
    permissionMap.courts.view,
    permissionMap.courts.list,
    permissionMap.courts.search,
    permissionMap.lawyers.view,
    permissionMap.lawyers.list,
    permissionMap.notifications.viewOwn,
    permissionMap.events.view,
    permissionMap.settings.view,
  ),
};

export const isPrivilegedRole = (roleName: string) => ["super_admin", "admin"].includes(roleName);
