import React from 'react';
import DashboardPage from '@features/dashboard/pages/DashboardPage';
import DashboardHome from '@features/dashboard/components/dashboard/Dashboard';
import ClientUnClientList from '@features/clients/pages/ClientUnClientList';
import LegalServicList from '@features/legal-services/pages/LegalServicList';
import SearchCourt from '@features/reports/components/Reports/SearchCourt';
import CaseSettingsIndex from '@features/courts/components/Courts/case_index.component';
import FinanceLedgerPage from '@features/finance/pages/FinanceLedgerPage';
import CaseFinanceSummaryPage from '@features/finance/pages/CaseFinanceSummaryPage';
import CreateTransactionPage from '@features/finance/pages/CreateTransactionPage';
import LegalCaseList from '@features/legal-cases/pages/LegalCaseList';
import LegalCaseDetails from '@features/legal-cases/components/LegalCases/LegalCaseDetails';
import ProfileUser from '@features/settings/components/Settings/ProfileUser';
import LawyerList from '@features/lawyers/pages/LawyerList';
import ManagmentSettings from '@features/settings/pages/ManagmentSettings';
import SearchCourtsApi from '@features/courts/pages/SearchCourtsApi';
import IconsGalleryPage from '@features/icons-gallery/pages/IconsGalleryPage';
import UiQaPage from '@features/ui-qa/pages/UiQaPage';
import AdminAccessManagementPage from '@features/admin/pages/AdminAccessManagementPage';
import QaRbacPage from '@features/admin/pages/QaRbacPage';
import ReportsIndex from '@features/reports/pages/ReportsIndex';
import ReportsOverview from '@features/reports/pages/ReportsOverview';
import SessionsReport from '@features/reports/pages/SessionsReport';
import ProceduresReport from '@features/reports/pages/ProceduresReport';
import ClientsReport from '@features/reports/pages/ClientsReport';
import CasesReport from '@features/reports/pages/CasesReport';
import ServicesReport from '@features/reports/pages/ServicesReport';
import DocumentsHubPage from '@features/documents/pages/DocumentsHubPage';
import PowerOfAttorneyPage from '@features/power-of-attorneys/pages/PowerOfAttorneyPage';

export const DashboardHomeRoutePage = () => <DashboardHome />;
export const DashboardShellRoutePage = () => <DashboardPage />;
export const CustomerServiceRoutePage = () => <ClientUnClientList />;
export const LegalServicesRoutePage = () => <LegalServicList />;
export const CourtSearchRoutePage = () => <SearchCourt />;
export const CaseSettingsRoutePage = () => <CaseSettingsIndex />;
export const FinanceLedgerRoutePage = () => <FinanceLedgerPage />;
export const CaseFinanceSummaryRoutePage = () => <CaseFinanceSummaryPage />;
export const CreateTransactionRoutePage = () => <CreateTransactionPage />;
export const LegalCasesRoutePage = () => <LegalCaseList />;
export const LegalCaseDetailsRoutePage = () => <LegalCaseDetails />;
export const ProfileRoutePage = () => <ProfileUser />;
export const LawyersRoutePage = () => <LawyerList />;
export const OfficeSettingsRoutePage = () => <ManagmentSettings />;
export const SearchCourtsApiRoutePage = () => <SearchCourtsApi />;
export const IconsGalleryRoutePage = () => <IconsGalleryPage />;
export const UiQaRoutePage = () => <UiQaPage />;
export const AdminAccessRoutePage = () => <AdminAccessManagementPage />;
export const QaRbacRoutePage = () => <QaRbacPage />;
export const ReportsRoutePage = () => <ReportsIndex />;
export const ReportsOverviewRoutePage = () => <ReportsOverview />;
export const SessionsReportRoutePage = () => <SessionsReport />;
export const ProceduresReportRoutePage = () => <ProceduresReport />;
export const ClientsReportRoutePage = () => <ClientsReport />;
export const CasesReportRoutePage = () => <CasesReport />;
export const ServicesReportRoutePage = () => <ServicesReport />;
export const DocumentsRoutePage = () => <DocumentsHubPage />;
export const PowerOfAttorneysRoutePage = () => <PowerOfAttorneyPage />;
